spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/oauth2
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  output:
    ansi:
      enabled: always

logging:
  level:
    org.hibernate.type: trace

jwt:
  secret-key: Z29nby10bS1zZXJ2ZXItZGxyamVvYW9yb3JodG9kZ290c3Atam9vbmdhbmduaW0teWVvbHNpbWhpaGFsZ2VveW8K

oauth:
  kakao:
    client-id: dc69b57a75a32d80850f2103a625908e
    url:
      auth: https://kauth.kakao.com
      api: https://kapi.kakao.com